use_frameworks!

platform :ios, '10.0'

target 'TMUIExtensions_Example' do
  pod 'TMUIExtensions', :path => '../'

  target 'TMUIExtensions_Tests' do
    inherit! :search_paths

    
  end
end

target 'TMUIExtensionsBinary' do

end
